version: '3'
services:
  
  mongo_srv:
    image: mongo:5.0
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
  
  messager:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongo_srv
  
volumes:
  mongodata: 